name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Node.js version from .nvmrc
        id: read-node-version
        run: |
          if [ -f "${{ github.workspace }}/.nvmrc" ]; then
            NODE_VERSION=$(cat ${{ github.workspace }}/.nvmrc)
            echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          else
            echo ".nvmrc file not found"
            exit 1
          fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web/build

  # Deployment job
  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
